### ISSUE TITLE
Grid is overdoing it

### ISSUE THREAD

**Issue by luukvanderduim** [nilgradisnik/markdown-rs#5]
Thanks for this nice tool!
I use a dark theme for use on the desktop. I use Adwaita-Dark on Xubuntu 19.10
It seems markdown-rs does not expect these color settings because grid gets in the way.
What would be the best way to cure this?
Thanks a bunch in advance!

![markdown-rs](https://user-images.githubusercontent.com/35066656/76166191-001d6280-615d-11ea-8b20-6123c39c1ebd.png)

**Comment by nilgradisnik** [comment]
Thanks for checking out this project! I didn't test it against dark theme, let me give it a go and I'll see if I can fix this.

**Comment by nilgradisnik** [comment]
I was able to reproduce this issue. I just removed the background grid since it doesn't render well with dark theme https://github.com/nilgradisnik/markdown-rs/commit/48ea497b556a8321874c97bbeb6451ce3b6b9e6a

**Comment by luukvanderduim** [comment]
A lot better!
Thank you very much

    Luuk

Op 04-04-2020 om 00:39 schreef Nil Gradisnik:
